### ISSUE TITLE
Flatten configuration further

### ISSUE THREAD

**Issue by udoprog** [udoprog/setmod#11]
Completely remove `[[irc.channel]]` in favor of a `[irc] channel` argument.

Move currency configuration to root of config.

We can now only configure the bot to be present in a single channel.

**Comment by udoprog** [comment]
New configuration (including currency) will go from this:

```toml
[irc]
bot = "setmod"
moderator_cooldown = "5s"
# whether to notify when viewers are rewarded with loyalty currency.
notify_rewards = false

[[irc.channels]]
name = "#setbac"
currency = {name = "ether"}
```

To this:

```toml
[irc]
bot = "setmod"
channel= "#setbac"
moderator_cooldown = "5s"
# whether to notify when viewers are rewarded with loyalty currency.
notify_rewards = false

[currency]
name = "ether"
```
