### ISSUE TITLE
Use Spotify's connect API to control music

### ISSUE THREAD

**Issue by udoprog** [udoprog/setmod#17]
This is probably better since it's guaranteed to be within Spotify's TOS.

**Comment by udoprog** [comment]
You can now configure the player to use the connect API like this:

```toml
[player]
type = "connect"
# Optional: if you don't want to use the default device. All devices are listed when the bot starts up
# device = "MEMPHIS"
```
